stages:
  - lint
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

lint:
  stage: lint
  script:
    - rm -fr build
    - ./gradlew ktlintFormat --console=rich
    - ./gradlew detekt --console=rich
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
    - androidmobileapi/build/reports/

build:
  stage: build
  script:
    - ./gradlew clean assemble --console=rich
  artifacts:
    paths:
     - androidmobileapi/build/outputs/aar/

unitTests:
  stage: test
  script:
    - ./gradlew -x lint check --console=rich