stages:
  - lint
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - .gradle/wrapper
    - .gradle/notifications
    - .gradle/caches

.prepare_sdk: &prepare_sdk |
  export ANDROID_HOME=/Users/4d/builds/khqL5qp1/0/qmobile/android/android-sdk
  export ANDROID_SDK_HOME=$ANDROID_HOME
  export ANDROID_SDK_ROOT=$ANDROID_HOME
  export PATH=$PATH:$ANDROID_HOME/platform-tools/
  export PATH=$PATH:$ANDROID_HOME/tools/
  export PATH=$PATH:$ANDROID_HOME/tools/bin/
  export PATH=$PATH:$ANDROID_AVD_HOME
  
lint:
  stage: lint
  script:
    - *prepare_sdk
#    - rm -fr .gradle/caches
#    - rm -fr build
    - ./gradlew ktlintFormat --console=rich
    - ./gradlew detekt --console=rich
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
    - qmobileapi/build/reports/
  tags:
    - osx

build:
  stage: build
  script:
    - *prepare_sdk
#    - ./gradlew clean --console=rich
    - ./gradlew assemble --console=rich
    - ./gradlew artifactoryPublish --console=rich
  tags:
    - osx
  artifacts:
    paths:
     - qmobileapi/build/outputs/aar/

unitTests:
  stage: test
  script:
    - *prepare_sdk
    - ./gradlew jacocoTestReport --console=rich
  #  - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' qmobileapi/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv
  tags:
    - osx