variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_SDK_TOOLS: "4333796"
  ANDROID_BUILD_TOOLS: "29.0.2"

stages:
  - lint
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

lint:
  stage: lint
  script:
    - rm -fr build
    - ./gradlew ktlintFormat --console=rich
    - ./gradlew detekt --console=rich
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
    - qmobileapi/build/reports/

.prepare_sdk: &prepare_sdk |
  export ANDROID_HOME=$PWD/../android-sdk
  export ANDROID_SDK_HOME=$PWD/../android-sdk
  export ANDROID_SDK_ROOT=$PWD/../android-sdk
  export PATH=$PATH:$ANDROID_HOME/platform-tools/
  export PATH=$PATH:$ANDROID_HOME/tools/
  export PATH=$PATH:$ANDROID_HOME/tools/bin/
  export PATH=$PATH:$ANDROID_AVD_HOME

buildLinux:
  stage: build
  script:
    - *prepare_sdk
    - ./gradlew clean --console=rich
    - ./gradlew assemble --console=rich
    - ./gradlew artifactoryPublish --console=rich
  artifacts:
    paths:
     - qmobileapi/build/outputs/aar/

unitTests:
  stage: test
  script:
    - *prepare_sdk
    - ./gradlew -x lint jacocoTestReport --console=rich
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' qmobileapi/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv