variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_SDK_TOOLS: "4333796"
  ANDROID_BUILD_TOOLS: "29.0.2"

stages:
  - lint
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - touch local.properties

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

lint:
  stage: lint
  script:
    - rm -fr build
    - ./gradlew ktlintFormat --console=rich
    - ./gradlew detekt --console=rich
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
    - androidmobileapi/build/reports/

build:
  stage: build
  script:
    - ./gradlew clean --console=rich
    - ./gradlew assemble --console=rich
    - ./gradlew artifactoryPublish --console=rich
  artifacts:
    paths:
     - androidmobileapi/build/outputs/aar/

unitTests:
  stage: test
  script:
    - ./gradlew -x lint check --console=rich
    #- ./gradlew jacocoTestReport
    #- awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' androidmobileapi/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv